name: CI Devops

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '8'
                distribution: 'temurin'
            - name: compile
              run: |
                mvn package  

            - name: run unit tests
              run: |
                mvn clean verify