name: CI Devops

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '8'
                distribution: 'temurin'
            - name: compile
              run: |
                mvn package  

            - name: run unit tests
              run: |
                mvn clean verify

            - name: Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '17'
                distribution: 'temurin'   

            - name: Analisis SonarCloud
              run: |
                mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
                -Dsonar.token=${{ secrets.TOKEN_SONAR }} \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=leonardonorambuena \
                -Dsonar.projectKey=leonardonorambuena_microservicio-java

            - name: SonarQube check gate
              uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
              with:
                scanMetadataReportFile: target/sonar/report-task.txt
                env:
                TOKEN_SONAR: ${{ secrets.TOKEN_SONAR }}