name: CI Devops

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '8'
                distribution: 'temurin'
            - name: compile
              run: |
                mvn package  

            - name: run unit tests
              run: |
                mvn clean verify

            - name: Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '17'
                distribution: 'temurin'   

            - name: Analisis SonarCloud
              run: |
                mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
                -Dsonar.token=${{ secrets.TOKEN_SONAR }} \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=leonardonorambuena \
                -Dsonar.projectKey=leonardonorambuena_microservicio-java
            # Triggering SonarQube analysis as results of it are required by Quality Gate check.
            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }} 
              # Check the Quality Gate status.
            - name: SonarQube Quality Gate check
              id: sonarqube-quality-gate-check
              uses: sonarsource/sonarqube-quality-gate-action@master
                # Force to fail step after specific time.
              timeout-minutes: 5
              env:
                SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}