name: CI Devops

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '8'
                distribution: 'temurin'
            - name: compile
              run: |
                mvn package  

            - name: run unit tests
              run: |
                mvn clean verify

            - name: Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '17'
                distribution: 'temurin'   

            - name: Analisis SonarCloud
              run: |
                mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
                -Dsonar.token=${{ secrets.TOKEN_SONAR }} \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.organization=leonardonorambuena \
                -Dsonar.projectKey=leonardonorambuena_microservicio-java

            - name: SonarQube check gate
              uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
              with:
                scanMetadataReportFile: target/sonar/report-task.txt
              env:
                SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
                SONAR_HOST_URL: https://sonarcloud.io

            - name: Builder de Docker
              uses: docker/setup-buildx-action@v3
        
            - name: Login Docker
              uses: docker/login-action@v3.1.0
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push microservicio
              uses: docker/build-push-action@v5
              with:
                context: .
                platforms: linux/amd64,linux/arm64
                push: true
                tags: ${{ secrets.DOCKER_USER }}/devops-foundation:latest
                

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Despliegue del micro servicio
              run: |
                kubectl apply -f deploy.yaml